ALTER TABLE services ADD COLUMN p95_millis INTEGER NOT NULL DEFAULT 0;
ALTER TABLE services ADD COLUMN availability DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE services ADD COLUMN throughput_rps INTEGER NOT NULL DEFAULT 0;
