---
apiVersion: v1
kind: Secret
metadata:
  name:  keycloak-user-sharon
type: Opaque
data:
  password: c2hhcm9u # base64-encoded value of "sharon"
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: ham4log-user-sharon
spec:
  realmRef:
    name: ham4log
    kind: KeycloakRealm
  username: sharon
  firstName: "Sharon"
  lastName: "Greene"
  email: "sharon.greene@example.com"
  enabled: true
  emailVerified: true
  keepResource: true
  roles:
    - offline_access
  groups:
    - Readers
  attributes:
    foo: "bar"
    baz: "jazz"
  passwordSecret:
    name: keycloak-user-sharon
    key: password
