---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app
spec:
  releaseName: app
  chart:
    spec:
      chart: service-capture-backend
      version: 0.0.0
      sourceRef:
        kind: HelmRepository
        name: polecatworks
  interval: 50m
  install:
    remediation:
      retries: 3
  values: {}
    # # imagePullSecrets:
    # #   - name: polecatworks-classic
    # be:
    #   webservice:
    #     prefix: /log4ham/v0
    #   image:
    #     repository: ghcr.io/polecatworks/log4ham-be
    #     tag: main
    #     pullPolicy: Always
    #   configs:
    #     persistence:
    #       db:
    #         connection:
    #           url_file: db/url
    #           username_file: db/username
    #           password_file: db/password
    #   volumes:
    #     - name: configs
    #       configMap:
    #         name: '{{ template "service-capture-backend.fullname" . }}-be'
    #     - name: objects
    #       emptyDir:
    #         sizeLimit: 500Mi
    #     - name: secrets
    #       projected:
    #         sources:
    #           - secret:
    #               optional: false
    #               name: log4ham-pg
    #               items:
    #                 - key: DB_USER
    #                   path: db/username
    #                 - key: DB_PASS
    #                   path: db/password
    #                 - key: CONNECTION_STRING
    #                   path: db/url
    # devsecops:
    #   RequestAuthentication:
    #     jwtRules: []
    #       # - issuer: http://dev.k8s/auth/realms/dev
    #       #   jwksUri: http://keycloak.security/auth/realms/dev/protocol/openid-connect/certs
    #       #   forwardOriginalToken: true
    #       #   audiences:
    #       #     - app-cake
    #   AuthorizationPolicy:
    #     rules: []
    #     # - to:
    #     #   - operation:
    #     #       methods:
    #     #       - GET
    #     #       paths:
    #     #       - /cake/v0/chunks
    #     #   when:
    #     #   - key: request.auth.claims[resource_access][app-pie][roles]
    #     #     values:
    #     #     - chunks-read
    #     # - to:
    #     #   - operation:
    #     #       methods:
    #     #       - POST
    #     #       - PUT
    #     #       paths:
    #     #       - /cake/v0/chunks
    #     #   when:
    #     #   - key: request.auth.claims[resource_access][app-pie][roles]
    #     #     values:
    #     #     - chunks-write
