---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: service-capture-backend
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/service-capture/helm/service-capture-backend
  ref:
    tag: 0.0.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cap-api
spec:
  releaseName: cap-api
  chartRef:
    kind: OCIRepository
    name: service-capture-backend
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/service-capture-backend
      tag: main
      pullPolicy: Always # Dev ONLY
    secretName: db0-service-cap-user
    configs:
      persistence:
        db:
          connection:
            url: postgres://cnpg-db0-cluster-rw.dbs.svc.cluster.local:5432/service_cap
            username_file: db/username
            password_file: db/password
    devsecops:
      RequestAuthentication:
        jwtRules:
          - issuer: http://keycloak.k8s/auth/realms/dev
            jwksUri: http://keycloak-keycloakx-http.auth/auth/realms/dev/protocol/openid-connect/certs
            forwardOriginalToken: true
            audiences:
              - service-capture
      AuthorizationPolicy:
        rules:
          - to:
              - operation:
                  methods:
                    - GET
                  paths:
                    - /capture/users
                    - /capture/services
                    - /capture/dependencies
                    - /capture/hello
            when:
              - key: request.auth.claims[resource_access][service-capture][roles]
                values:
                  - service-read
          - to:
              - operation:
                  methods:
                    - POST
                    - PUT
                    - DELETE
                  paths:
                    - /capture/users
                    - /capture/services
                    - /capture/dependencies
            when:
              - key: request.auth.claims[resource_access][service-capture][roles]
                values:
                  - service-write
