---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClientScope
metadata:
  name: client-audience
spec:
  name: client-audience
  realmRef:
    name: dev
    kind: KeycloakRealm
  description: Client mappers to audience
  protocol: openid-connect
  protocolMappers:
    - name: app-pie-as-audience
      protocol: openid-connect
      protocolMapper: oidc-audience-mapper
      config:
        "included.client.audience": app-pie
        "id.token.claim": "false"
        "lightweight.claim": "false"
        "access.token.claim": "true"
        "introspection.token.claim": "true"
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: app-pie
spec:
  realmRef:
    name: dev
    kind: KeycloakRealm
  advancedProtocolMappers: true
  clientId: app-pie
  name: app pie Service Account
  description: App pie Service Account
  clientRoles:
    - chunks-read
    - chunks-write
    - chunks-delete
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: app-ui
spec:
  realmRef:
    name: dev
    kind: KeycloakRealm
  advancedProtocolMappers: true
  clientId: app-ui
  name: app UI Oauth Client
  description: "App UI OAuth Client"
  public: true
  standardFlowEnabled: true
  directAccess: true
  implicitFlowEnabled: true
  optionalClientScopes:
    - client-audience
  # webUrl: https://argocd.example.com
  # adminUrl: https://admin.example.com
  # homeUrl: /home/
  # defaultClientScopes:
  #   - groups
  redirectUris:
    - "*"
  webOrigins:
    - "*"
  #   - /url2/*
