---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: service-capture-backend
spec:
  interval: 60m
  url: oci://ghcr.io/polecatworks/service-capture/helm/service-capture-backend
  ref:
    tag: 0.0.0
